# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Assay Development Educational Series
email: michael.sachs@nih.gov
description: > # this means to ignore newlines until "baseurl:"
  This is a series of lessons on the logistical and statistical 
  issues related to the development and evaluation of biomarkers
  for use in oncology. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sachsmc.github.io/assay-education" # the base hostname & protocol for your site
twitter_username: theNCI
github_username:  sachsmc
gems: [us_web_design_standards]
sass:
    sass_dir: _sass
exclude: [README.md]

# Build settings
markdown: kramdown
